export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const FETCH_USER_FOLLOWING = 'FETCH_USER_FOLLOWING';

export const FETCH_USERS_DATA = 'FETCH_USERS_DATA';
export const FETCH_USERS_POSTS = 'FETCH_USERS_POSTS';
export const FETCH_USERS_FOLLOWING = 'FETCH_USERS_FOLLOWING';

export const CLEAR_DATA = 'CLEAR_DATA';
